[tools]
# Stack
node = "latest"
pnpm = "latest"
bun = "latest"

# Tools
gh = "latest"

[settings]
# Enable extra features
experimental = true
# Ignore idiomatic version files
idiomatic_version_file_enable_tools = []
