[tasks."test"]
depends = ["test/unit", "test/tz"]

[tasks."test/unit"]
run = "pnpm vitest --run"

[tasks."test/unit:watch"]
run = "pnpm vitest"

[tasks."test/tz/base"]
run = "./scripts/test/tz.sh"

[tasks."test/tz/offset"]
run = "bun ./scripts/test/tzOffset.ts"

[tasks."test/tz/iana"]
run = "bun ./scripts/test/tzIANA.ts"

[tasks."test/smoke"]
run = "./scripts/test/smoke.sh"

[tasks."test/types"]
run = "./scripts/test/types.sh"

[tasks."locale-snapshots"]
run = "pnpm tsx ./scripts/build/localeSnapshots/index.ts"
env = { TZ = "utc" }

[tasks."locale-snapshots:test"]
run = "pnpm tsx ./scripts/build/localeSnapshots/index.ts --test"
env = { TZ = "utc" }
